/*
 * Copyright IBM Corp. 2015
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.ibm.watson.developer_cloud.professor_languo.ingestion.indexing;

import java.util.Collection;
import java.util.Properties;
import java.util.Set;

import org.apache.lucene.document.Document;
import org.apache.lucene.document.FieldType;

import com.ibm.watson.developer_cloud.professor_languo.exception.IngestionException;
import com.ibm.watson.developer_cloud.professor_languo.model.stack_exchange.StackExchangeThread;

/**
 * A DocumentMapper is responsible for transforming a {@link StackExchangeThread} into a Lucene
 * {@link Document}
 *
 */
public interface DocumentMapper {

  /**
   * Initialize the {@link DocumentMapper}, specifying any necessary properties
   *
   * @param properties - A collection of {@link Properties}
   * @throws IngestionException
   */
  public void initialize(Properties properties) throws IngestionException;

  /**
   * Create a new {@link Document} for the given {@link StackExchangeThread}
   *
   * @param question - The {@link StackExchangeThread} to transform
   * @return - A Lucene {@link Document}
   * @throws IngestionException
   */
  public Document createDocument(StackExchangeThread question) throws IngestionException;

  /**
   * @return A Collection of Lucene {@link FieldType FieldTypes} for each of the fields generated by
   *         this DocumentMapper
   */
  public Collection<FieldType> getFieldTypes();

  /**
   * @return A Set of names for each of the fields produced by this DocumentMapper
   */
  public Set<String> getFieldNames();

}
